%YAML:1.0
---
operator_armor_yaw_offset: 0
operator_armor_pitch_offset: 0
operator_buff_yaw_offset_18: 0
operator_buff_pitch_offset_18: 0
operator_buff_yaw_offset_30: 0
operator_buff_pitch_offset_30: 0
