%YAML:1.0
---
######################这个文件里面是一些比如你在一辆车上需要常修改的变量，
######################比如video_debug你需要常开关，如果不是，就直接定义宏，这样就可以稍微减少一些资源
#是否使用相机
CAMERA: 1
#是否开启qt的VideoDebug界面
VIDEODEBUG: 0
#是否开启标定程序
CALIBRATE: 0
#是否记录录像
RECORDER: 0
#是否记录log
LOG: 1
#是否开启opencv的TBB加速
HAVE_TBB: 1
#设置进入VIDEODEBUG程序时的状态
INDEX: 1  #ArmorMode = 0, EnergyBuffMode = 1, LobMode = 2, BuffDisturb = 3
#设置是否开启回放
BACKTREACK: 1
#是否需要Debug听串口控制
USART: 0
